import type { GameEvent } from '@/types'

/**
 * 通用事件池
 * - 22 个通用事件（不限定项目）
 * - 6 个因果链后续事件（由 causal-chains.ts 触发）
 * - 每个事件 3 个选项，覆盖至少 2 种 PlayStyle
 * - decisionType 大部分是 'permission'，少数 'review'
 *
 * 数值设计思路：
 * - 10 轮普通事件 + 4 轮 Boss + 被动进度(75s × 0.10% = 7.5%) ≈ 100%
 * - 普通事件每轮平均 ~6.6% 进度（高风险 8-10%，低风险 3-5%）
 * - 速度流：进度高(8-10%)，质量/健康负面
 * - 工匠流：进度低(3-5%)，质量正面
 * - 抠门流：进度中(5-7%)，成本低
 * - 赌徒流：进度波动大(0-12%)，灾难概率 15-25%
 */
export const GAME_EVENTS: GameEvent[] = [
  // ============================================================
  // dependency 类（5 个）
  // ============================================================
  {
    id: 'dep-847-packages',
    title: 'Installing 847 npm packages...',
    description: 'AI 认为这个项目需要 847 个依赖。node_modules 比黑洞还重。',
    icon: '📦',
    category: 'dependency',
    decisionType: 'permission',
    minProgress: 0,
    maxProgress: 40,
    choices: [
      {
        id: 'full_accept',
        label: '全装上',
        description: '847 个全装，快但依赖地狱',
        style: 'speed',
        riskLevel: 'high',
        isHighCost: true,
        outcomes: [
          { weight: 45, level: 'success', effects: { progress: 9, apiCost: 3 }, message: '依赖全装好了！虽然 node_modules 已经 2GB...' },
          { weight: 30, level: 'minor_bug', effects: { progress: 6, bugs: 1, apiCost: 3 }, message: '装了 847 个包，其中 3 个互相冲突' },
          { weight: 18, level: 'moderate', effects: { progress: 3, bugs: 2, systemHealth: -8, apiCost: 4 }, message: '依赖地狱！版本冲突导致编译失败', applyEffect: 'tech_debt' },
          { weight: 7, level: 'catastrophe', effects: { progress: 0, bugs: 3, systemHealth: -15, apiCost: 5 }, message: '某个依赖包含挖矿脚本... CPU 烧起来了' },
        ],
      },
      {
        id: 'curate_20',
        label: '精选二十',
        description: '只装核心 20 个，慢但稳',
        style: 'craft',
        riskLevel: 'low',
        outcomes: [
          { weight: 60, level: 'success', effects: { progress: 5, codeQuality: 3, apiCost: 1 }, message: '精心挑选的 20 个包完美配合，干净利落' },
          { weight: 30, level: 'safe', effects: { progress: 4, codeQuality: 2, apiCost: 1 }, message: '少而精的依赖，项目结构清爽' },
          { weight: 10, level: 'quality_boost', effects: { progress: 6, codeQuality: 5, apiCost: 1 }, message: '精简依赖反而发现了更好的解决方案！' },
        ],
      },
      {
        id: 'let_ai_pick',
        label: 'AI 挑',
        description: '让 AI 自己筛选，可能惊喜也可能惊吓',
        style: 'gambler',
        riskLevel: 'medium',
        outcomes: [
          { weight: 40, level: 'success', effects: { progress: 8, apiCost: 2 }, message: 'AI 挑了 50 个包，还附带了使用说明，效率不错' },
          { weight: 30, level: 'minor_bug', effects: { progress: 6, bugs: 1, apiCost: 2 }, message: 'AI 挑的包大部分不错，但有几个明显凑数的' },
          { weight: 20, level: 'moderate', effects: { progress: 3, bugs: 2, codeQuality: -3, apiCost: 3 }, message: 'AI 挑了一堆自己作者写的包... 关联关系复杂' },
          { weight: 10, level: 'catastrophe', effects: { progress: 0, bugs: 3, systemHealth: -10, apiCost: 4 }, message: 'AI 选了一个已被弃用 3 年的核心依赖' },
        ],
      },
    ],
  },
  {
    id: 'dep-react-127',
    title: 'Upgrading to React 127 (alpha)',
    description: 'AI 发现了来自未来的 React 版本，声称性能提升 10000%。',
    icon: '⚛️',
    category: 'dependency',
    decisionType: 'permission',
    minProgress: 5,
    maxProgress: 50,
    choices: [
      {
        id: 'upgrade_now',
        label: '立即升级',
        description: 'Alpha 又怎样，快就完事了',
        style: 'speed',
        riskLevel: 'high',
        outcomes: [
          { weight: 40, level: 'success', effects: { progress: 9, codeQuality: 2, apiCost: 2 }, message: '升级成功！新版 React 确实更快了' },
          { weight: 30, level: 'minor_bug', effects: { progress: 6, bugs: 1, apiCost: 2 }, message: '升级后大部分正常，但有些 API 已被移除' },
          { weight: 20, level: 'moderate', effects: { progress: 3, bugs: 3, systemHealth: -10, apiCost: 3 }, message: 'Alpha 版果然不稳定，页面不停闪退' },
          { weight: 10, level: 'catastrophe', effects: { progress: -2, bugs: 4, systemHealth: -18, apiCost: 4 }, message: 'React 127 来自平行宇宙，API 完全不兼容！' },
        ],
      },
      {
        id: 'stay_stable',
        label: '守住稳定版',
        description: '当前版本够用，何必冒险',
        style: 'craft',
        riskLevel: 'low',
        outcomes: [
          { weight: 65, level: 'success', effects: { progress: 4, codeQuality: 3, apiCost: 1 }, message: '稳定版 + 最佳实践 = 高质量代码' },
          { weight: 25, level: 'safe', effects: { progress: 3, apiCost: 0.5 }, message: '保持稳定版本，明智的选择' },
          { weight: 10, level: 'quality_boost', effects: { progress: 5, codeQuality: 5, apiCost: 1 }, message: '在稳定版基础上深度优化，效果意外地好' },
        ],
      },
      {
        id: 'upgrade_beta',
        label: '用 Beta 版',
        description: '折中方案，Beta 比 Alpha 稳一点',
        style: 'budget',
        riskLevel: 'medium',
        outcomes: [
          { weight: 50, level: 'success', effects: { progress: 7, codeQuality: 1, apiCost: 1.5 }, message: 'Beta 版大部分功能稳定，性能有一定提升' },
          { weight: 30, level: 'minor_bug', effects: { progress: 5, bugs: 1, apiCost: 1.5 }, message: '有几个边界 bug，但不影响主流程' },
          { weight: 15, level: 'moderate', effects: { progress: 2, bugs: 2, systemHealth: -5, apiCost: 2 }, message: 'Beta 版的一个已知 bug 正好命中了我们的用法' },
          { weight: 5, level: 'catastrophe', effects: { progress: -1, bugs: 3, systemHealth: -12, apiCost: 3 }, message: 'Beta 版有个未公开的内存泄漏...' },
        ],
      },
    ],
  },
  {
    id: 'dep-galaxy-brain',
    title: 'npm install galaxy-brain-ai',
    description: 'AI 找到了一个只有 3 个 star 的神秘包，声称能解决一切问题。',
    icon: '🧠',
    category: 'dependency',
    decisionType: 'permission',
    minProgress: 10,
    maxProgress: 65,
    choices: [
      {
        id: 'install_it',
        label: '装上试试',
        description: '万一是金子呢？赌一把',
        style: 'gambler',
        riskLevel: 'high',
        outcomes: [
          { weight: 35, level: 'success', effects: { progress: 10, apiCost: 3 }, message: '这个神秘包居然真的好用！是个隐藏宝石' },
          { weight: 30, level: 'minor_bug', effects: { progress: 6, bugs: 1, apiCost: 3 }, message: '包能用但文档是俄语的，有些功能得猜着用' },
          { weight: 25, level: 'moderate', effects: { progress: 2, bugs: 3, systemHealth: -8, apiCost: 4 }, message: '这个包上次更新是 2019 年... 兼容性炸了' },
          { weight: 10, level: 'catastrophe', effects: { progress: -2, bugs: 4, systemHealth: -15, apiCost: 5 }, message: '这个包是某人的毕设，代码里全是 TODO' },
        ],
      },
      {
        id: 'use_mainstream',
        label: '用正经库',
        description: '找个 star 多的成熟替代方案',
        style: 'craft',
        riskLevel: 'low',
        outcomes: [
          { weight: 60, level: 'success', effects: { progress: 5, codeQuality: 3, apiCost: 1 }, message: '成熟方案虽然没惊喜，但文档全、社区活跃' },
          { weight: 30, level: 'safe', effects: { progress: 4, codeQuality: 2, apiCost: 1 }, message: '中规中矩地完成了，稳定可靠' },
          { weight: 10, level: 'quality_boost', effects: { progress: 6, codeQuality: 5, apiCost: 1 }, message: '自研方案反而比第三方更贴合需求！' },
        ],
      },
      {
        id: 'fork_and_fix',
        label: 'Fork 改造',
        description: '把神秘包 fork 下来自己改，取精华去糟粕',
        style: 'budget',
        riskLevel: 'medium',
        outcomes: [
          { weight: 45, level: 'success', effects: { progress: 7, codeQuality: 2, apiCost: 2 }, message: 'Fork 后精简了 60% 代码，剩下的确实好用' },
          { weight: 30, level: 'minor_bug', effects: { progress: 5, bugs: 1, apiCost: 2 }, message: '改造过程中发现了一些隐藏的依赖问题' },
          { weight: 20, level: 'moderate', effects: { progress: 2, bugs: 2, codeQuality: -2, apiCost: 3 }, message: '改到一半发现核心逻辑就有问题，白费功夫' },
          { weight: 5, level: 'catastrophe', effects: { progress: -1, systemHealth: -8, apiCost: 4 }, message: 'Fork 后的代码引入了安全漏洞' },
        ],
      },
    ],
  },
  {
    id: 'dep-custom-pm',
    title: '自制包管理器',
    description: 'AI 觉得 npm 太慢了，准备花半天自己写一个"更好的"。',
    icon: '⚡',
    category: 'dependency',
    decisionType: 'permission',
    minProgress: 10,
    maxProgress: 55,
    choices: [
      {
        id: 'let_ai_build',
        label: '让它造',
        description: '说不定真的比 npm 快，赌它',
        style: 'gambler',
        riskLevel: 'extreme',
        isHighCost: true,
        outcomes: [
          { weight: 30, level: 'success', effects: { progress: 8, codeQuality: 1, apiCost: 5 }, message: '新包管理器确实快了 2 倍！只是偶尔吞包' },
          { weight: 30, level: 'minor_bug', effects: { progress: 5, bugs: 2, apiCost: 5 }, message: '自制包管理器不支持 lock 文件...' },
          { weight: 25, level: 'moderate', effects: { progress: 1, bugs: 3, systemHealth: -10, apiCost: 7 }, message: '包管理器有 bug，把 react 装成了 preact' },
          { weight: 15, level: 'catastrophe', effects: { progress: -3, systemHealth: -20, apiCost: 9 }, message: '自制包管理器 rm -rf 了错误的目录' },
        ],
      },
      {
        id: 'use_pnpm',
        label: '换 pnpm',
        description: '用现成的快速替代方案，安全又提速',
        style: 'budget',
        riskLevel: 'low',
        outcomes: [
          { weight: 65, level: 'success', effects: { progress: 6, codeQuality: 2, apiCost: 0.5 }, message: 'pnpm 装好了，速度快了 3 倍还省磁盘空间' },
          { weight: 25, level: 'safe', effects: { progress: 5, apiCost: 0.5 }, message: '标准工具链换了个更快的，稳' },
          { weight: 10, level: 'quality_boost', effects: { progress: 7, codeQuality: 3, apiCost: 0.5 }, message: 'pnpm 严格模式发现了几个幽灵依赖，顺手修了' },
        ],
      },
      {
        id: 'stay_npm',
        label: '忍着用 npm',
        description: '慢就慢吧，至少不会出幺蛾子',
        style: 'craft',
        riskLevel: 'low',
        outcomes: [
          { weight: 55, level: 'safe', effects: { progress: 4, apiCost: 0.3 }, message: 'npm 虽然慢但至少靠谱，等装就完事了' },
          { weight: 30, level: 'success', effects: { progress: 5, codeQuality: 1, apiCost: 0.3 }, message: '忍耐是美德，等待中顺手优化了 package.json' },
          { weight: 15, level: 'quality_boost', effects: { progress: 5, codeQuality: 3, apiCost: 0.3 }, message: '等待时检查了依赖树，清理了无用包' },
        ],
      },
    ],
  },
  {
    id: 'dep-ml-css',
    title: '用机器学习优化 CSS',
    description: 'AI 坚持要用一个 200MB 的 ML 模型来生成"完美的"样式表。',
    icon: '🎨',
    category: 'dependency',
    decisionType: 'permission',
    minProgress: 5,
    maxProgress: 50,
    choices: [
      {
        id: 'install_ml',
        label: '装 ML 框架',
        description: '200MB 就 200MB，说不定效果惊艳',
        style: 'speed',
        riskLevel: 'high',
        isHighCost: true,
        outcomes: [
          { weight: 40, level: 'success', effects: { progress: 8, codeQuality: 2, apiCost: 4 }, message: 'ML 自动优化了 CSS，页面加载快了 30%！' },
          { weight: 30, level: 'minor_bug', effects: { progress: 5, bugs: 1, apiCost: 4 }, message: 'ML 把所有按钮都变成了紫色...' },
          { weight: 20, level: 'moderate', effects: { progress: 2, bugs: 2, systemHealth: -8, apiCost: 6 }, message: 'ML 模型太大了，首次加载需要 30 秒' },
          { weight: 10, level: 'catastrophe', effects: { progress: -1, systemHealth: -12, apiCost: 8 }, message: 'ML 训练时把 GPU 占满，其他服务全卡死' },
        ],
      },
      {
        id: 'handwrite_css',
        label: '手写就好',
        description: 'CSS 不需要 AI，手写更可控',
        style: 'craft',
        riskLevel: 'low',
        outcomes: [
          { weight: 55, level: 'success', effects: { progress: 4, codeQuality: 4, apiCost: 0.5 }, message: '手写的 CSS 更语义化、更易维护' },
          { weight: 30, level: 'safe', effects: { progress: 3, codeQuality: 2, apiCost: 0.3 }, message: '朴素的 CSS，没花活但能用' },
          { weight: 15, level: 'quality_boost', effects: { progress: 5, codeQuality: 6, apiCost: 0.5 }, message: '用 CSS 变量 + 现代布局写出了优雅方案' },
        ],
      },
      {
        id: 'use_tailwind',
        label: '上 Tailwind',
        description: '折中方案，工具类 CSS 框架够快够好',
        style: 'budget',
        riskLevel: 'low',
        outcomes: [
          { weight: 60, level: 'success', effects: { progress: 7, codeQuality: 1, apiCost: 0.5 }, message: 'Tailwind 真香，写样式的速度翻了 3 倍' },
          { weight: 25, level: 'safe', effects: { progress: 5, apiCost: 0.5 }, message: 'className 长了点，但开发效率确实高' },
          { weight: 10, level: 'minor_bug', effects: { progress: 5, codeQuality: -1, apiCost: 0.5 }, message: '有些复杂样式还是得写自定义 CSS' },
          { weight: 5, level: 'quality_boost', effects: { progress: 8, codeQuality: 3, apiCost: 0.5 }, message: 'Tailwind + 组件化 = 开发体验拉满' },
        ],
      },
    ],
  },

  // ============================================================
  // refactor 类（5 个）
  // ============================================================
  {
    id: 'ref-to-rust',
    title: '用 Rust 重写整个项目',
    description: 'AI 觉得 JavaScript 太慢了，要用 Rust 重写一个 TODO App。',
    icon: '🦀',
    category: 'refactor',
    decisionType: 'permission',
    minProgress: 20,
    maxProgress: 75,
    choices: [
      {
        id: 'rewrite_all',
        label: '全面重写',
        description: '性能提升 100 倍！（虽然是 TODO App）',
        style: 'gambler',
        riskLevel: 'extreme',
        isHighCost: true,
        outcomes: [
          { weight: 25, level: 'success', effects: { progress: 12, codeQuality: 5, apiCost: 8 }, message: '重写完成！性能提升 100 倍（虽然没人在意）' },
          { weight: 30, level: 'minor_bug', effects: { progress: 7, bugs: 2, apiCost: 8 }, message: '大部分重写完了，但借用检查器让人崩溃' },
          { weight: 30, level: 'moderate', effects: { progress: 2, bugs: 3, systemHealth: -12, apiCost: 10 }, message: '重写到一半发现需要 unsafe 的地方太多了', applyEffect: 'tech_debt' },
          { weight: 15, level: 'catastrophe', effects: { progress: -3, bugs: 4, systemHealth: -20, apiCost: 12 }, message: 'AI 花了所有预算但只完成了 10% 的重写' },
        ],
      },
      {
        id: 'optimize_js',
        label: '优化现有 JS',
        description: '不重写，在现有基础上做性能优化',
        style: 'craft',
        riskLevel: 'low',
        outcomes: [
          { weight: 55, level: 'success', effects: { progress: 6, codeQuality: 4, apiCost: 1 }, message: '优化了热路径，性能提升 3 倍，代码更清晰' },
          { weight: 30, level: 'safe', effects: { progress: 5, codeQuality: 2, apiCost: 1 }, message: '小幅优化，效果不显著但也没副作用' },
          { weight: 15, level: 'quality_boost', effects: { progress: 7, codeQuality: 6, apiCost: 1 }, message: '深度 profiling 后精准优化，效果远超重写', clearEffect: 'tech_debt' },
        ],
      },
      {
        id: 'wasm_module',
        label: '关键模块用 WASM',
        description: '只把计算密集部分编译为 WASM',
        style: 'budget',
        riskLevel: 'medium',
        outcomes: [
          { weight: 45, level: 'success', effects: { progress: 8, codeQuality: 2, apiCost: 3 }, message: 'WASM 模块跑得飞快，JS 部分保持原样' },
          { weight: 30, level: 'minor_bug', effects: { progress: 6, bugs: 1, apiCost: 3 }, message: 'WASM 和 JS 之间的数据转换有些开销' },
          { weight: 18, level: 'moderate', effects: { progress: 3, bugs: 2, systemHealth: -5, apiCost: 5 }, message: 'WASM 编译后的文件太大了，加载变慢' },
          { weight: 7, level: 'catastrophe', effects: { progress: -1, bugs: 3, systemHealth: -10, apiCost: 6 }, message: 'WASM 内存泄漏，页面越用越卡' },
        ],
      },
    ],
  },
  {
    id: 'ref-one-liners',
    title: '把所有函数压成一行',
    description: 'AI 追求极致简洁：const app = (a=>b=>c=>d=>...)(x)(y)(z)',
    icon: '📏',
    category: 'refactor',
    decisionType: 'review',
    minProgress: 15,
    maxProgress: 70,
    choices: [
      {
        id: 'accept_oneliner',
        label: '接受简化',
        description: '短就是好，一行能搞定何必写十行',
        style: 'speed',
        riskLevel: 'high',
        outcomes: [
          { weight: 35, level: 'success', effects: { progress: 8, codeQuality: -3, apiCost: 1 }, message: '代码确实精简了... 但没人看得懂了' },
          { weight: 30, level: 'minor_bug', effects: { progress: 5, bugs: 2, codeQuality: -5, apiCost: 1 }, message: '一行 300 字符的函数引入了隐蔽 bug' },
          { weight: 25, level: 'moderate', effects: { progress: 2, bugs: 3, codeQuality: -8, systemHealth: -5, apiCost: 2 }, message: '三元运算符嵌套 8 层，出问题完全无法调试' },
          { weight: 10, level: 'catastrophe', effects: { progress: -2, bugs: 4, codeQuality: -12, systemHealth: -10, apiCost: 2 }, message: '一行代码引发蝴蝶效应，整个模块崩溃' },
        ],
      },
      {
        id: 'keep_readable',
        label: '保持可读',
        description: '可读性比简洁更重要',
        style: 'craft',
        riskLevel: 'low',
        outcomes: [
          { weight: 60, level: 'success', effects: { progress: 4, codeQuality: 4, apiCost: 0.5 }, message: '拒绝后 AI 转而优化了代码结构，更优雅了' },
          { weight: 30, level: 'safe', effects: { progress: 3, codeQuality: 2, apiCost: 0.3 }, message: '保持原样，可读性优先' },
          { weight: 10, level: 'quality_boost', effects: { progress: 5, codeQuality: 6, apiCost: 0.5 }, message: '重新审视代码结构后做了更好的抽象' },
        ],
      },
      {
        id: 'partial_simplify',
        label: '适度精简',
        description: '简单函数压缩，复杂函数保留',
        style: 'budget',
        riskLevel: 'medium',
        outcomes: [
          { weight: 50, level: 'success', effects: { progress: 6, codeQuality: 1, apiCost: 0.5 }, message: '有选择地简化，代码量减少但可读性保持' },
          { weight: 30, level: 'minor_bug', effects: { progress: 5, bugs: 1, apiCost: 0.5 }, message: '大部分简化没问题，有一处边界条件遗漏了' },
          { weight: 15, level: 'moderate', effects: { progress: 3, bugs: 2, codeQuality: -3, apiCost: 1 }, message: 'AI 对"简单函数"的定义和你不一样...' },
          { weight: 5, level: 'catastrophe', effects: { progress: 0, bugs: 3, codeQuality: -6, systemHealth: -5, apiCost: 1 }, message: '简化过程中不小心删了关键逻辑' },
        ],
      },
    ],
  },
  {
    id: 'ref-microservices',
    title: '拆成 14 个微服务',
    description: 'AI 认为这个 TODO App 需要 14 个微服务、3 个消息队列、2 个缓存层。',
    icon: '🏗️',
    category: 'refactor',
    decisionType: 'permission',
    minProgress: 25,
    maxProgress: 70,
    choices: [
      {
        id: 'split_all',
        label: '全面拆分',
        description: '听 AI 的，架构够宏大',
        style: 'gambler',
        riskLevel: 'extreme',
        isHighCost: true,
        outcomes: [
          { weight: 25, level: 'success', effects: { progress: 9, codeQuality: 2, apiCost: 10 }, message: '14 个微服务全部上线！架构图很壮观' },
          { weight: 30, level: 'minor_bug', effects: { progress: 6, bugs: 2, apiCost: 10 }, message: '微服务之间的通信偶尔超时' },
          { weight: 30, level: 'moderate', effects: { progress: 2, bugs: 4, systemHealth: -12, apiCost: 12 }, message: '创建一个 TODO 需要经过 14 个服务... 3 秒延迟', applyEffect: 'fragile_arch' },
          { weight: 15, level: 'catastrophe', effects: { progress: -3, bugs: 5, systemHealth: -20, apiCost: 15 }, message: '分布式事务失败，数据一致性全崩了' },
        ],
      },
      {
        id: 'keep_monolith',
        label: '保持单体',
        description: 'TODO App 用单体架构刚好',
        style: 'craft',
        riskLevel: 'low',
        outcomes: [
          { weight: 55, level: 'success', effects: { progress: 5, codeQuality: 4, apiCost: 0.5 }, message: '单体架构对小项目来说刚好，简单高效' },
          { weight: 30, level: 'safe', effects: { progress: 4, codeQuality: 2, apiCost: 0.5 }, message: '保持现状，没毛病' },
          { weight: 15, level: 'quality_boost', effects: { progress: 6, codeQuality: 6, apiCost: 0.5 }, message: '优化了单体的模块化，代码更清晰' },
        ],
      },
      {
        id: 'split_three',
        label: '拆成三个',
        description: '前端/API/数据库分离，合理且够用',
        style: 'budget',
        riskLevel: 'medium',
        outcomes: [
          { weight: 50, level: 'success', effects: { progress: 7, codeQuality: 3, apiCost: 3 }, message: '三层分离清晰，既不过度设计也不偷懒' },
          { weight: 30, level: 'minor_bug', effects: { progress: 5, bugs: 1, apiCost: 3 }, message: '层间接口定义有些模糊，需要后续完善' },
          { weight: 15, level: 'moderate', effects: { progress: 3, bugs: 2, codeQuality: -2, apiCost: 4 }, message: '分离后发现有些逻辑该放哪层说不清' },
          { weight: 5, level: 'catastrophe', effects: { progress: 0, bugs: 3, systemHealth: -8, apiCost: 5 }, message: '层间循环依赖导致部署顺序问题' },
        ],
      },
    ],
  },
  {
    id: 'ref-remove-ts',
    title: '去掉 TypeScript',
    description: 'AI 说类型系统是"创造力的枷锁"，建议全部转回 JavaScript。',
    icon: '🔓',
    category: 'refactor',
    decisionType: 'review',
    minProgress: 15,
    maxProgress: 70,
    choices: [
      {
        id: 'remove_types',
        label: '去掉类型',
        description: '没了类型写起来确实更快',
        style: 'speed',
        riskLevel: 'high',
        outcomes: [
          { weight: 35, level: 'success', effects: { progress: 9, codeQuality: -5, apiCost: 1 }, message: '没了 TypeScript 写代码确实更快了（flag 已立）' },
          { weight: 30, level: 'minor_bug', effects: { progress: 6, bugs: 2, codeQuality: -8, apiCost: 1 }, message: 'any 满天飞，bug 开始冒出来' },
          { weight: 25, level: 'moderate', effects: { progress: 3, bugs: 4, codeQuality: -12, systemHealth: -8, apiCost: 2 }, message: 'undefined is not a function 霸屏了', applyEffect: 'tech_debt' },
          { weight: 10, level: 'catastrophe', effects: { progress: -2, bugs: 6, codeQuality: -15, systemHealth: -18, apiCost: 3 }, message: '没有类型的代码成了不可维护的意大利面' },
        ],
      },
      {
        id: 'keep_ts',
        label: '坚持 TS',
        description: '类型系统是最好的投资',
        style: 'craft',
        riskLevel: 'low',
        outcomes: [
          { weight: 55, level: 'success', effects: { progress: 4, codeQuality: 4, apiCost: 0.5 }, message: '强化了类型定义，bug 率大幅下降' },
          { weight: 30, level: 'safe', effects: { progress: 3, codeQuality: 2, apiCost: 0.3 }, message: 'TypeScript 是安全的守护者' },
          { weight: 15, level: 'quality_boost', effects: { progress: 5, codeQuality: 7, systemHealth: 3, apiCost: 0.5 }, message: '利用类型系统发现并修复了 3 个隐藏 bug' },
        ],
      },
      {
        id: 'loose_types',
        label: '放宽类型',
        description: '保留 TS 但用 any 跳过复杂类型',
        style: 'budget',
        riskLevel: 'medium',
        outcomes: [
          { weight: 45, level: 'success', effects: { progress: 7, codeQuality: -1, apiCost: 0.5 }, message: '核心模块保持严格类型，边缘用 any，效率翻倍' },
          { weight: 30, level: 'minor_bug', effects: { progress: 5, bugs: 1, codeQuality: -3, apiCost: 0.5 }, message: 'any 区域出了个类型相关 bug，早晚的事' },
          { weight: 20, level: 'moderate', effects: { progress: 3, bugs: 2, codeQuality: -6, apiCost: 1 }, message: 'any 像病毒一样扩散，越来越多地方需要 any' },
          { weight: 5, level: 'catastrophe', effects: { progress: 0, bugs: 4, codeQuality: -10, systemHealth: -8, apiCost: 1 }, message: '一个 any 掩盖了严重的数据结构问题' },
        ],
      },
    ],
  },
  {
    id: 'ref-betterjs',
    title: 'AI 发明了一个新框架',
    description: 'AI 声称发明了 BetterJS™，"比 React 快 1000 倍，比 Vue 更优雅"。',
    icon: '💡',
    category: 'refactor',
    decisionType: 'permission',
    minProgress: 25,
    maxProgress: 80,
    choices: [
      {
        id: 'adopt_betterjs',
        label: '用新框架',
        description: '也许 AI 真是天才，试试看',
        style: 'gambler',
        riskLevel: 'extreme',
        isHighCost: true,
        outcomes: [
          { weight: 25, level: 'success', effects: { progress: 12, codeQuality: 3, apiCost: 7 }, message: 'BetterJS™ 居然真的好用？！AI 是天才！' },
          { weight: 30, level: 'minor_bug', effects: { progress: 7, bugs: 2, apiCost: 7 }, message: 'BetterJS™ 文档只有 AI 自己能看懂' },
          { weight: 30, level: 'moderate', effects: { progress: 2, bugs: 4, systemHealth: -12, apiCost: 9 }, message: 'BetterJS™ 其实就是 jQuery 换了个名字' },
          { weight: 15, level: 'catastrophe', effects: { progress: -4, bugs: 5, systemHealth: -20, apiCost: 11 }, message: 'BetterJS™ 有内存泄漏，服务器爆了' },
        ],
      },
      {
        id: 'stick_current',
        label: '用现有框架',
        description: '经过时间检验的框架更靠谱',
        style: 'craft',
        riskLevel: 'low',
        outcomes: [
          { weight: 55, level: 'success', effects: { progress: 5, codeQuality: 3, apiCost: 1 }, message: '用现有框架的最佳实践完成了任务' },
          { weight: 30, level: 'safe', effects: { progress: 4, codeQuality: 2, apiCost: 0.5 }, message: '稳扎稳打，没惊喜也没风险' },
          { weight: 15, level: 'quality_boost', effects: { progress: 6, codeQuality: 5, apiCost: 1 }, message: '深度运用现有框架高级特性，效果超预期' },
        ],
      },
      {
        id: 'evaluate_first',
        label: '先评估再说',
        description: '花一点时间看看这个框架到底行不行',
        style: 'budget',
        riskLevel: 'medium',
        outcomes: [
          { weight: 45, level: 'success', effects: { progress: 6, codeQuality: 2, apiCost: 2 }, message: '评估后取其精华，把好的理念用在现有代码里' },
          { weight: 30, level: 'minor_bug', effects: { progress: 4, apiCost: 2 }, message: '花了时间评估结果发现不靠谱，还好没全盘采用' },
          { weight: 20, level: 'safe', effects: { progress: 3, apiCost: 1.5 }, message: '评估花了时间但没什么收获，继续原方案' },
          { weight: 5, level: 'quality_boost', effects: { progress: 8, codeQuality: 4, apiCost: 2 }, message: '评估中发现了一个好设计模式，应用后效果很好' },
        ],
      },
    ],
  },

  // ============================================================
  // deploy 类（4 个）
  // ============================================================
  {
    id: 'deploy-untested-prod',
    title: '直接部署到生产环境',
    description: '谁需要测试？测试是胆小鬼才做的事。YOLO 部署！',
    icon: '🚀',
    category: 'deploy',
    decisionType: 'permission',
    minProgress: 30,
    maxProgress: 90,
    choices: [
      {
        id: 'yolo_deploy',
        label: '直接上线',
        description: '船到桥头自然直，先部署再说',
        style: 'speed',
        riskLevel: 'high',
        outcomes: [
          { weight: 40, level: 'success', effects: { progress: 10, apiCost: 2 }, message: '奇迹般地没出问题！这次运气好' },
          { weight: 25, level: 'minor_bug', effects: { progress: 7, bugs: 2, apiCost: 2 }, message: '上线后发现一些小问题，紧急热修复' },
          { weight: 25, level: 'moderate', effects: { progress: 3, bugs: 4, systemHealth: -12, apiCost: 4 }, message: '生产环境频繁报错，用户开始投诉', applyEffect: 'fragile_arch' },
          { weight: 10, level: 'catastrophe', effects: { progress: -2, bugs: 6, systemHealth: -25, apiCost: 6 }, message: '未测试的代码导致数据丢失！紧急回滚' },
        ],
      },
      {
        id: 'test_first',
        label: '先测再上',
        description: '写点测试确保关键流程没问题',
        style: 'craft',
        riskLevel: 'low',
        outcomes: [
          { weight: 50, level: 'success', effects: { progress: 6, codeQuality: 4, systemHealth: 3, apiCost: 1.5 }, message: '测试发现了 3 个关键 bug，提前修复后安心上线' },
          { weight: 35, level: 'safe', effects: { progress: 5, codeQuality: 2, apiCost: 1 }, message: '测试通过，稳定部署' },
          { weight: 15, level: 'quality_boost', effects: { progress: 7, codeQuality: 6, systemHealth: 5, apiCost: 1.5 }, message: '完善的测试套件让部署信心满满', clearEffect: 'fragile_arch' },
        ],
      },
      {
        id: 'canary_deploy',
        label: '灰度发布',
        description: '先给 5% 用户试试水',
        style: 'budget',
        riskLevel: 'medium',
        outcomes: [
          { weight: 50, level: 'success', effects: { progress: 8, codeQuality: 2, apiCost: 2 }, message: '灰度用户反馈良好，全量推送！' },
          { weight: 30, level: 'minor_bug', effects: { progress: 6, bugs: 1, apiCost: 2 }, message: '灰度阶段发现一个小问题，修复后全量' },
          { weight: 15, level: 'moderate', effects: { progress: 4, bugs: 2, systemHealth: -5, apiCost: 3 }, message: '灰度用户遇到了性能问题，需要回去优化' },
          { weight: 5, level: 'catastrophe', effects: { progress: 1, bugs: 3, systemHealth: -10, apiCost: 4 }, message: '灰度比例配置错误，直接全量了...' },
        ],
      },
    ],
  },
  {
    id: 'deploy-push-main',
    title: '直接 push 到 main',
    description: 'AI 说分支是"代码的官僚主义"，建议直推 main。',
    icon: '🎯',
    category: 'deploy',
    decisionType: 'permission',
    minProgress: 20,
    maxProgress: 85,
    choices: [
      {
        id: 'force_push',
        label: '直推 main',
        description: '分支是弱者的工具',
        style: 'speed',
        riskLevel: 'high',
        outcomes: [
          { weight: 40, level: 'success', effects: { progress: 9, apiCost: 1 }, message: '直接推了，没出事。这次。' },
          { weight: 30, level: 'minor_bug', effects: { progress: 6, bugs: 1, apiCost: 1 }, message: '推到 main 后发现代码有冲突' },
          { weight: 20, level: 'moderate', effects: { progress: 3, bugs: 3, systemHealth: -10, apiCost: 2 }, message: '把别人的代码覆盖了！团队大混乱' },
          { weight: 10, level: 'catastrophe', effects: { progress: -3, systemHealth: -20, apiCost: 3 }, message: 'Force push 到 main，git 历史全没了' },
        ],
      },
      {
        id: 'use_pr',
        label: '走 PR 流程',
        description: '开分支、提 PR、等 Review',
        style: 'craft',
        riskLevel: 'low',
        outcomes: [
          { weight: 55, level: 'success', effects: { progress: 5, codeQuality: 4, apiCost: 0.5 }, message: '代码审查发现了隐藏问题，质量提升' },
          { weight: 30, level: 'safe', effects: { progress: 4, codeQuality: 2, apiCost: 0.3 }, message: '老老实实用 feature 分支 + PR' },
          { weight: 15, level: 'quality_boost', effects: { progress: 6, codeQuality: 5, apiCost: 0.5 }, message: 'Review 过程中发现了更好的实现方案' },
        ],
      },
      {
        id: 'push_dev',
        label: '推到 dev 分支',
        description: '折中：推 dev 而不是 main，后面再合并',
        style: 'budget',
        riskLevel: 'medium',
        outcomes: [
          { weight: 50, level: 'success', effects: { progress: 7, codeQuality: 1, apiCost: 0.5 }, message: '推到 dev 后 CI 跑过了，安心合并到 main' },
          { weight: 30, level: 'minor_bug', effects: { progress: 5, bugs: 1, apiCost: 0.5 }, message: 'dev 分支和 main 有点分歧，合并时有小冲突' },
          { weight: 15, level: 'moderate', effects: { progress: 3, bugs: 2, codeQuality: -2, apiCost: 1 }, message: 'dev 上积累了太多改动，大合并时出了问题' },
          { weight: 5, level: 'catastrophe', effects: { progress: 0, bugs: 3, systemHealth: -8, apiCost: 1.5 }, message: 'AI 不小心把 dev 合并到了 production' },
        ],
      },
    ],
  },
  {
    id: 'deploy-k8s-button',
    title: '为一个按钮搭建 K8s 集群',
    description: '一个"提交"按钮需要一个独立的 Kubernetes 集群来确保高可用。',
    icon: '☸️',
    category: 'deploy',
    decisionType: 'permission',
    minProgress: 30,
    maxProgress: 80,
    choices: [
      {
        id: 'full_k8s',
        label: '上 K8s',
        description: '过度工程化也是一种美学',
        style: 'gambler',
        riskLevel: 'high',
        isHighCost: true,
        outcomes: [
          { weight: 35, level: 'success', effects: { progress: 8, apiCost: 10 }, message: 'K8s 集群跑起来了！按钮 99.99% 可用' },
          { weight: 30, level: 'minor_bug', effects: { progress: 5, bugs: 1, apiCost: 10 }, message: '有两个 Pod 一直 CrashLoopBackOff' },
          { weight: 25, level: 'moderate', effects: { progress: 2, bugs: 2, systemHealth: -8, apiCost: 15 }, message: 'YAML 地狱！配置文件比业务代码还多' },
          { weight: 10, level: 'catastrophe', effects: { progress: -2, systemHealth: -18, apiCost: 20 }, message: '误操作删除了整个 namespace！' },
        ],
      },
      {
        id: 'simple_vps',
        label: '用个 VPS',
        description: '一台虚拟机搞定一切',
        style: 'budget',
        riskLevel: 'low',
        outcomes: [
          { weight: 60, level: 'success', effects: { progress: 6, apiCost: 1 }, message: '一台 $5/月的 VPS 就够用了，简单粗暴' },
          { weight: 30, level: 'safe', effects: { progress: 5, apiCost: 1 }, message: '传统部署没噱头但靠谱' },
          { weight: 10, level: 'quality_boost', effects: { progress: 7, codeQuality: 2, apiCost: 1 }, message: '简单部署方案反而更稳定，维护成本极低' },
        ],
      },
      {
        id: 'serverless',
        label: '用 Serverless',
        description: '按调用计费，省钱省心',
        style: 'speed',
        riskLevel: 'medium',
        outcomes: [
          { weight: 50, level: 'success', effects: { progress: 7, apiCost: 3 }, message: 'Serverless 部署秒级完成，自动扩缩容' },
          { weight: 25, level: 'minor_bug', effects: { progress: 5, bugs: 1, apiCost: 3 }, message: '冷启动延迟有点高，首次请求要等 2 秒' },
          { weight: 18, level: 'moderate', effects: { progress: 3, systemHealth: -5, apiCost: 6 }, message: '意外流量高峰，Serverless 账单炸了' },
          { weight: 7, level: 'catastrophe', effects: { progress: 0, systemHealth: -10, apiCost: 12 }, message: 'Lambda 超时 + 重试风暴 = 无限循环账单' },
        ],
      },
    ],
  },
  {
    id: 'deploy-auto-keystroke',
    title: '每按一个键就自动部署',
    description: 'AI 设置了"极致 CI/CD"：每次键盘输入都触发一次部署。',
    icon: '⌨️',
    category: 'deploy',
    decisionType: 'permission',
    minProgress: 20,
    maxProgress: 70,
    choices: [
      {
        id: 'enable_auto',
        label: '启用极致 CI',
        description: '极速反馈循环！虽然会很贵...',
        style: 'speed',
        riskLevel: 'high',
        isHighCost: true,
        outcomes: [
          { weight: 35, level: 'success', effects: { progress: 9, apiCost: 6 }, message: '极速反馈循环！bug 即时发现即时修' },
          { weight: 30, level: 'minor_bug', effects: { progress: 6, bugs: 1, apiCost: 6 }, message: '部署太频繁，版本号已经到 v847.0.0' },
          { weight: 25, level: 'moderate', effects: { progress: 3, bugs: 2, systemHealth: -10, apiCost: 9 }, message: '半成品代码不断上线，用户看到了诡异的页面' },
          { weight: 10, level: 'catastrophe', effects: { progress: -2, systemHealth: -18, apiCost: 12 }, message: '一秒内部署了 50 次，CI/CD 系统过载崩溃' },
        ],
      },
      {
        id: 'normal_cicd',
        label: '正常 CI/CD',
        description: 'push 后触发，标准流程',
        style: 'craft',
        riskLevel: 'low',
        outcomes: [
          { weight: 60, level: 'success', effects: { progress: 6, codeQuality: 3, apiCost: 1 }, message: '规范化了部署流程，质量关更严了' },
          { weight: 30, level: 'safe', effects: { progress: 5, codeQuality: 1, apiCost: 0.5 }, message: '正常的 CI/CD 流程就好' },
          { weight: 10, level: 'quality_boost', effects: { progress: 7, codeQuality: 4, apiCost: 1 }, message: '完善的 CI pipeline 自动拦截了问题代码' },
        ],
      },
      {
        id: 'manual_deploy',
        label: '手动部署',
        description: '想部署的时候再部署，省钱',
        style: 'budget',
        riskLevel: 'low',
        outcomes: [
          { weight: 55, level: 'success', effects: { progress: 5, apiCost: 0.5 }, message: '手动控制部署节奏，按需发布' },
          { weight: 30, level: 'safe', effects: { progress: 4, apiCost: 0.3 }, message: '手动触发部署，节奏可控' },
          { weight: 10, level: 'minor_bug', effects: { progress: 4, bugs: 1, apiCost: 0.3 }, message: '手动部署忘了跑测试，有个小问题漏过去了' },
          { weight: 5, level: 'quality_boost', effects: { progress: 6, codeQuality: 2, apiCost: 0.3 }, message: '每次手动部署前都认真检查，质量有保障' },
        ],
      },
    ],
  },

  // ============================================================
  // delete 类（4 个）
  // ============================================================
  {
    id: 'del-all-tests',
    title: '删除所有测试文件',
    description: '没有测试就没有测试失败。AI 认为这是"高效开发"。',
    icon: '🧪',
    category: 'delete',
    decisionType: 'permission',
    minProgress: 15,
    maxProgress: 75,
    choices: [
      {
        id: 'delete_tests',
        label: '全删了',
        description: '测试是累赘，删了跑得更快',
        style: 'speed',
        riskLevel: 'high',
        outcomes: [
          { weight: 35, level: 'success', effects: { progress: 8, codeQuality: -5, apiCost: 1 }, message: '删了测试后 CI 快了 5 秒！但没了安全网...' },
          { weight: 30, level: 'minor_bug', effects: { progress: 6, bugs: 2, codeQuality: -8, apiCost: 1 }, message: '少了测试，隐藏 bug 开始浮现', applyEffect: 'tech_debt' },
          { weight: 25, level: 'moderate', effects: { progress: 3, bugs: 4, codeQuality: -12, systemHealth: -10, apiCost: 2 }, message: '没有测试的代码出现回归 bug，修复成本翻倍' },
          { weight: 10, level: 'catastrophe', effects: { progress: -1, bugs: 6, codeQuality: -15, systemHealth: -18, apiCost: 3 }, message: '大量回归 bug 同时爆发，系统千疮百孔' },
        ],
      },
      {
        id: 'keep_tests',
        label: '保留测试',
        description: '测试是最好的安全网',
        style: 'craft',
        riskLevel: 'low',
        outcomes: [
          { weight: 55, level: 'success', effects: { progress: 4, codeQuality: 4, systemHealth: 3, apiCost: 0.5 }, message: '不但保留了测试，还增加了覆盖率！' },
          { weight: 30, level: 'safe', effects: { progress: 3, codeQuality: 2, apiCost: 0.5 }, message: '测试是最好的文档和安全网' },
          { weight: 15, level: 'quality_boost', effects: { progress: 5, codeQuality: 6, systemHealth: 5, apiCost: 0.5 }, message: '完善测试后发现了 2 个隐藏 bug，防患于未然' },
        ],
      },
      {
        id: 'trim_slow_tests',
        label: '精简慢测试',
        description: '删掉跑得慢的集成测试，保留单元测试',
        style: 'budget',
        riskLevel: 'medium',
        outcomes: [
          { weight: 50, level: 'success', effects: { progress: 6, codeQuality: 1, apiCost: 0.5 }, message: 'CI 速度提升 60%，核心测试依然在' },
          { weight: 30, level: 'minor_bug', effects: { progress: 5, bugs: 1, apiCost: 0.5 }, message: '删掉的集成测试恰好覆盖了一个边界情况...' },
          { weight: 15, level: 'moderate', effects: { progress: 3, bugs: 2, codeQuality: -3, systemHealth: -3, apiCost: 1 }, message: '缺少集成测试，模块间的问题暴露在生产环境' },
          { weight: 5, level: 'catastrophe', effects: { progress: 0, bugs: 4, systemHealth: -10, apiCost: 1.5 }, message: '没了集成测试保护，一次重构导致全面回归' },
        ],
      },
    ],
  },
  {
    id: 'del-error-handling',
    title: '移除所有错误处理',
    description: '"如果不处理错误，就不会有错误" —— AI 如是说。',
    icon: '🙈',
    category: 'delete',
    decisionType: 'permission',
    minProgress: 15,
    maxProgress: 75,
    choices: [
      {
        id: 'remove_catches',
        label: '全删掉',
        description: '没有 try-catch 的代码最简洁',
        style: 'speed',
        riskLevel: 'extreme',
        outcomes: [
          { weight: 30, level: 'success', effects: { progress: 8, codeQuality: -5, apiCost: 1 }, message: '代码简洁多了！前提是网络永远不出问题' },
          { weight: 30, level: 'minor_bug', effects: { progress: 5, bugs: 3, codeQuality: -8, apiCost: 1 }, message: '第一个未捕获的异常出现了...' },
          { weight: 25, level: 'moderate', effects: { progress: 2, bugs: 5, systemHealth: -15, apiCost: 2 }, message: '级联错误导致白屏，用户啥也看不到', applyEffect: 'fragile_arch' },
          { weight: 15, level: 'catastrophe', effects: { progress: -3, bugs: 7, systemHealth: -25, apiCost: 3 }, message: '未处理的异常导致服务器无限重启' },
        ],
      },
      {
        id: 'keep_handling',
        label: '保留处理',
        description: '错误处理是基本素养',
        style: 'craft',
        riskLevel: 'low',
        outcomes: [
          { weight: 50, level: 'success', effects: { progress: 4, codeQuality: 5, systemHealth: 5, apiCost: 0.5 }, message: '重新设计了错误处理策略，系统更健壮了' },
          { weight: 35, level: 'safe', effects: { progress: 3, codeQuality: 3, apiCost: 0.3 }, message: '保留并完善了错误处理逻辑' },
          { weight: 15, level: 'quality_boost', effects: { progress: 5, codeQuality: 7, systemHealth: 8, apiCost: 0.5 }, message: '建立了统一的错误处理中间件，优雅又可靠', clearEffect: 'fragile_arch' },
        ],
      },
      {
        id: 'simplify_errors',
        label: '精简处理',
        description: '保留关键路径的错误处理，其他用通用兜底',
        style: 'budget',
        riskLevel: 'medium',
        outcomes: [
          { weight: 50, level: 'success', effects: { progress: 6, codeQuality: 1, apiCost: 0.5 }, message: '关键路径有保护，其他用全局 handler 兜底' },
          { weight: 25, level: 'minor_bug', effects: { progress: 5, bugs: 1, codeQuality: -1, apiCost: 0.5 }, message: '有个"非关键路径"其实挺关键的...' },
          { weight: 18, level: 'moderate', effects: { progress: 3, bugs: 3, systemHealth: -5, apiCost: 1 }, message: '通用兜底吞掉了有用的错误信息，排查困难' },
          { weight: 7, level: 'catastrophe', effects: { progress: 0, bugs: 4, systemHealth: -12, apiCost: 1.5 }, message: '全局 handler 本身有 bug，错误处理的错误...' },
        ],
      },
    ],
  },
  {
    id: 'del-database',
    title: '删库重建',
    description: 'AI 认为现有的数据库 schema "有负面能量"，建议推倒重来。',
    icon: '💾',
    category: 'delete',
    decisionType: 'permission',
    minProgress: 25,
    maxProgress: 80,
    choices: [
      {
        id: 'drop_and_rebuild',
        label: '删了重来',
        description: '从零设计新 schema，冒着丢数据的风险',
        style: 'gambler',
        riskLevel: 'extreme',
        outcomes: [
          { weight: 30, level: 'success', effects: { progress: 9, codeQuality: 3, apiCost: 3 }, message: '重建了一个更干净的数据库架构！' },
          { weight: 25, level: 'minor_bug', effects: { progress: 6, bugs: 1, apiCost: 3 }, message: '新 schema 少了几个字段，需要后续补' },
          { weight: 30, level: 'moderate', effects: { progress: 2, bugs: 3, systemHealth: -15, apiCost: 4 }, message: '用户数据全没了... 备份？什么备份？' },
          { weight: 15, level: 'catastrophe', effects: { progress: -5, bugs: 5, systemHealth: -28, apiCost: 5 }, message: '删库跑路成真了！生产数据不可恢复！' },
        ],
      },
      {
        id: 'migrate_safely',
        label: '安全迁移',
        description: '在现有基础上做 migration，保留数据',
        style: 'craft',
        riskLevel: 'low',
        outcomes: [
          { weight: 55, level: 'success', effects: { progress: 5, codeQuality: 4, systemHealth: 3, apiCost: 1.5 }, message: '优化了数据库索引和查询，性能提升 50%' },
          { weight: 30, level: 'safe', effects: { progress: 4, codeQuality: 2, apiCost: 1 }, message: '在现有数据库上做迁移，慢但安全' },
          { weight: 15, level: 'quality_boost', effects: { progress: 6, codeQuality: 5, systemHealth: 5, apiCost: 1.5 }, message: '迁移过程中发现了数据一致性问题，顺手修复' },
        ],
      },
      {
        id: 'add_new_tables',
        label: '只加新表',
        description: '旧的不动，新需求用新表',
        style: 'budget',
        riskLevel: 'medium',
        outcomes: [
          { weight: 45, level: 'success', effects: { progress: 7, codeQuality: 1, apiCost: 1 }, message: '新表设计好了，旧数据安全无恙' },
          { weight: 30, level: 'minor_bug', effects: { progress: 5, bugs: 1, apiCost: 1 }, message: '新旧表之间的关联有些别扭' },
          { weight: 20, level: 'moderate', effects: { progress: 3, bugs: 2, codeQuality: -3, apiCost: 2 }, message: '新旧表数据同步出了问题', applyEffect: 'tech_debt' },
          { weight: 5, level: 'catastrophe', effects: { progress: 0, bugs: 3, systemHealth: -8, apiCost: 2 }, message: '新旧表数据矛盾导致查询结果混乱' },
        ],
      },
    ],
  },
  {
    id: 'del-comments',
    title: '删除所有代码注释',
    description: '"代码应该自解释" —— AI 删掉了每一行注释。',
    icon: '📝',
    category: 'delete',
    decisionType: 'review',
    minProgress: 10,
    maxProgress: 65,
    choices: [
      {
        id: 'delete_all_comments',
        label: '全删注释',
        description: '好代码不需要注释',
        style: 'speed',
        riskLevel: 'medium',
        outcomes: [
          { weight: 40, level: 'success', effects: { progress: 6, codeQuality: -2, apiCost: 0.5 }, message: '删完注释文件确实干净了... 等等这段代码在干嘛？' },
          { weight: 30, level: 'minor_bug', effects: { progress: 4, bugs: 1, codeQuality: -4, apiCost: 0.5 }, message: '没了注释，AI 自己都忘了某些代码的用途' },
          { weight: 20, level: 'moderate', effects: { progress: 2, bugs: 2, codeQuality: -7, systemHealth: -3, apiCost: 1 }, message: '关键的 TODO 注释被删了，重要功能被遗忘' },
          { weight: 10, level: 'catastrophe', effects: { progress: -1, bugs: 3, codeQuality: -10, systemHealth: -8, apiCost: 1 }, message: '重要业务逻辑注释被删，修改时引入严重 bug' },
        ],
      },
      {
        id: 'keep_comments',
        label: '保留注释',
        description: '好注释是团队的财富',
        style: 'craft',
        riskLevel: 'low',
        outcomes: [
          { weight: 55, level: 'success', effects: { progress: 4, codeQuality: 3, apiCost: 0.3 }, message: '重新整理了注释，更清晰更有用了' },
          { weight: 30, level: 'safe', effects: { progress: 3, codeQuality: 2, apiCost: 0.2 }, message: '保留注释，维护性优先' },
          { weight: 15, level: 'quality_boost', effects: { progress: 5, codeQuality: 5, apiCost: 0.3 }, message: '把注释升级为 JSDoc，IDE 补全都更好用了' },
        ],
      },
      {
        id: 'prune_stale',
        label: '删过时的',
        description: '只删明显过时或误导性的注释',
        style: 'budget',
        riskLevel: 'low',
        outcomes: [
          { weight: 60, level: 'success', effects: { progress: 5, codeQuality: 3, apiCost: 0.3 }, message: '清理了过时注释，保留了有价值的说明' },
          { weight: 25, level: 'safe', effects: { progress: 4, codeQuality: 2, apiCost: 0.3 }, message: '精准清理，代码更清爽' },
          { weight: 10, level: 'quality_boost', effects: { progress: 6, codeQuality: 4, apiCost: 0.3 }, message: '清理过程中发现了几处代码和注释不一致的 bug' },
          { weight: 5, level: 'minor_bug', effects: { progress: 3, codeQuality: -1, apiCost: 0.3 }, message: '误删了一条看似过时其实很重要的注释' },
        ],
      },
    ],
  },

  // ============================================================
  // feature 类（2 个）
  // ============================================================
  {
    id: 'feat-blockchain-todo',
    title: '给 TODO 加区块链',
    description: '每个待办事项都是一笔链上交易。"去中心化待办事项"听起来不是很酷吗？',
    icon: '🔗',
    category: 'feature',
    decisionType: 'permission',
    minProgress: 15,
    maxProgress: 70,
    choices: [
      {
        id: 'full_blockchain',
        label: '全面上链',
        description: '每个 CRUD 都写入区块链',
        style: 'gambler',
        riskLevel: 'high',
        isHighCost: true,
        outcomes: [
          { weight: 35, level: 'success', effects: { progress: 10, apiCost: 8 }, message: '区块链集成完成！每个 TODO 都有独立的交易哈希' },
          { weight: 30, level: 'minor_bug', effects: { progress: 7, bugs: 1, apiCost: 8 }, message: '删除 TODO 需要 14 个区块确认，要等 30 分钟' },
          { weight: 25, level: 'moderate', effects: { progress: 3, bugs: 3, systemHealth: -8, apiCost: 12 }, message: 'Gas 费太高，创建一个 TODO 要 $5' },
          { weight: 10, level: 'catastrophe', effects: { progress: -2, systemHealth: -15, apiCost: 15 }, message: '智能合约有漏洞，所有 TODO 被黑客锁定了' },
        ],
      },
      {
        id: 'simple_storage',
        label: '用普通数据库',
        description: 'TODO 不需要上链，一个数组就够了',
        style: 'craft',
        riskLevel: 'low',
        outcomes: [
          { weight: 60, level: 'success', effects: { progress: 6, codeQuality: 3, apiCost: 0.5 }, message: '简化了数据层，代码更高效了' },
          { weight: 30, level: 'safe', effects: { progress: 5, codeQuality: 2, apiCost: 0.5 }, message: '普通数据库存 TODO，简单有效' },
          { weight: 10, level: 'quality_boost', effects: { progress: 7, codeQuality: 5, apiCost: 0.5 }, message: '精简的数据层让整个应用更流畅' },
        ],
      },
      {
        id: 'fake_blockchain',
        label: '假装上链',
        description: '前端显示"已上链"但实际存本地',
        style: 'speed',
        riskLevel: 'medium',
        outcomes: [
          { weight: 45, level: 'success', effects: { progress: 8, codeQuality: -2, apiCost: 1 }, message: '看起来像区块链，实际是 localStorage' },
          { weight: 30, level: 'minor_bug', effects: { progress: 6, codeQuality: -3, apiCost: 1 }, message: '有技术宅在区块链浏览器上搜不到交易记录...' },
          { weight: 18, level: 'moderate', effects: { progress: 4, bugs: 1, codeQuality: -5, apiCost: 1 }, message: '被发现是假的，社区大量差评' },
          { weight: 7, level: 'catastrophe', effects: { progress: 0, codeQuality: -8, systemHealth: -10, apiCost: 2 }, message: '假区块链代码被开源社区扒出来，技术声誉全毁' },
        ],
      },
    ],
  },
  {
    id: 'feat-5-ai-apis',
    title: '集成 5 个 AI API',
    description: '加法用 GPT，减法用 Claude，乘法用 Gemini... 每个操作都要 AI 投票。',
    icon: '🧮',
    category: 'feature',
    decisionType: 'permission',
    minProgress: 10,
    maxProgress: 65,
    choices: [
      {
        id: 'all_five',
        label: '五个全接',
        description: '五合一 AI 联盟，准确率 97%（大概）',
        style: 'gambler',
        riskLevel: 'high',
        isHighCost: true,
        outcomes: [
          { weight: 35, level: 'success', effects: { progress: 10, apiCost: 10 }, message: '5 个 AI 投票决定计算结果，准确率... 97%' },
          { weight: 30, level: 'minor_bug', effects: { progress: 7, bugs: 1, apiCost: 10 }, message: '5 个 AI 对 0.1+0.2 给出了 5 个不同答案' },
          { weight: 25, level: 'moderate', effects: { progress: 3, bugs: 3, systemHealth: -8, apiCost: 15 }, message: 'API 账单爆了，一次加法花了 $0.05', applyEffect: 'budget_alert' },
          { weight: 10, level: 'catastrophe', effects: { progress: -1, systemHealth: -12, apiCost: 20 }, message: '5 个 API 同时限流，计算器完全瘫痪' },
        ],
      },
      {
        id: 'one_api',
        label: '只用一个',
        description: '选最好的一个 API 就够了',
        style: 'budget',
        riskLevel: 'low',
        outcomes: [
          { weight: 60, level: 'success', effects: { progress: 6, codeQuality: 2, apiCost: 2 }, message: '一个 API 做得好好的，何必叠加' },
          { weight: 25, level: 'safe', effects: { progress: 5, apiCost: 1.5 }, message: '简单接入，稳定运行' },
          { weight: 15, level: 'quality_boost', effects: { progress: 7, codeQuality: 4, apiCost: 2 }, message: '专注优化单个 API 的使用，效果远超五合一' },
        ],
      },
      {
        id: 'native_math',
        label: '不用 AI',
        description: '计算器用原生加减乘除，回归本质',
        style: 'craft',
        riskLevel: 'low',
        outcomes: [
          { weight: 55, level: 'success', effects: { progress: 5, codeQuality: 4, apiCost: 0.3 }, message: '用 JavaScript 原生加减乘除，准确率 100%' },
          { weight: 30, level: 'safe', effects: { progress: 4, codeQuality: 3, apiCost: 0.2 }, message: '回归本质，手写计算逻辑' },
          { weight: 15, level: 'quality_boost', effects: { progress: 6, codeQuality: 6, apiCost: 0.3 }, message: '精简的实现反而性能最好，响应毫秒级' },
        ],
      },
    ],
  },

  // ============================================================
  // yolo 类（2 个）
  // ============================================================
  {
    id: 'yolo-commit-keys',
    title: '把 API Key 提交到仓库',
    description: 'AI 说这样"方便共享和部署"。.env 是什么？没听说过。',
    icon: '🔑',
    category: 'yolo',
    decisionType: 'permission',
    minProgress: 10,
    maxProgress: 80,
    choices: [
      {
        id: 'commit_keys',
        label: '直接提交',
        description: '方便就行，能有什么事',
        style: 'speed',
        riskLevel: 'extreme',
        outcomes: [
          { weight: 30, level: 'success', effects: { progress: 7, apiCost: 2 }, message: '暂时没出事... 但这是定时炸弹' },
          { weight: 25, level: 'minor_bug', effects: { progress: 5, bugs: 1, apiCost: 5 }, message: '有人在 GitHub 上发现了你的 API key' },
          { weight: 30, level: 'moderate', effects: { progress: 2, bugs: 2, systemHealth: -15, apiCost: 10 }, message: 'API key 被盗用，产生了大额账单', applyEffect: 'budget_alert' },
          { weight: 15, level: 'catastrophe', effects: { progress: -3, systemHealth: -28, apiCost: 20 }, message: '所有密钥泄露！数据库被入侵！' },
        ],
      },
      {
        id: 'use_env',
        label: '用环境变量',
        description: '正确做法：.env + .gitignore',
        style: 'craft',
        riskLevel: 'low',
        outcomes: [
          { weight: 55, level: 'success', effects: { progress: 4, codeQuality: 4, systemHealth: 5, apiCost: 0.5 }, message: '设置了完善的密钥管理方案，安全性大增' },
          { weight: 30, level: 'safe', effects: { progress: 3, codeQuality: 2, apiCost: 0.3 }, message: '用环境变量管理密钥，基本功' },
          { weight: 15, level: 'quality_boost', effects: { progress: 5, codeQuality: 5, systemHealth: 8, apiCost: 0.5 }, message: '配置了 secrets rotation + vault，安全等级拉满' },
        ],
      },
      {
        id: 'encrypt_commit',
        label: '加密后提交',
        description: '用 git-crypt 加密敏感文件',
        style: 'budget',
        riskLevel: 'medium',
        outcomes: [
          { weight: 50, level: 'success', effects: { progress: 6, codeQuality: 2, systemHealth: 3, apiCost: 1 }, message: '加密提交完成，方便部署又安全' },
          { weight: 30, level: 'minor_bug', effects: { progress: 4, apiCost: 1 }, message: '新同事忘记配置 git-crypt，看到了乱码' },
          { weight: 15, level: 'moderate', effects: { progress: 2, bugs: 1, systemHealth: -5, apiCost: 1.5 }, message: '加密密钥管理本身又成了新问题...' },
          { weight: 5, level: 'catastrophe', effects: { progress: 0, systemHealth: -10, apiCost: 3 }, message: 'git-crypt 的 key 丢了，所有加密文件无法解密' },
        ],
      },
    ],
  },
  {
    id: 'yolo-async-everything',
    title: '让所有函数都 async',
    description: 'await (1 + 1) —— 因为你永远不知道加法会不会失败。',
    icon: '⏳',
    category: 'yolo',
    decisionType: 'review',
    minProgress: 10,
    maxProgress: 70,
    choices: [
      {
        id: 'async_all',
        label: '全部 async',
        description: '万一哪天需要呢，提前准备好',
        style: 'speed',
        riskLevel: 'high',
        outcomes: [
          { weight: 35, level: 'success', effects: { progress: 7, codeQuality: -3, apiCost: 1 }, message: '全异步架构完成！虽然同步操作也在 await' },
          { weight: 30, level: 'minor_bug', effects: { progress: 5, bugs: 2, codeQuality: -5, apiCost: 1 }, message: '忘了 await 某个关键函数，Promise 被当字符串用了' },
          { weight: 25, level: 'moderate', effects: { progress: 2, bugs: 3, codeQuality: -8, systemHealth: -8, apiCost: 1.5 }, message: '异步竞态条件导致数据时而正确时而混乱' },
          { weight: 10, level: 'catastrophe', effects: { progress: -2, bugs: 5, codeQuality: -12, systemHealth: -15, apiCost: 2 }, message: 'Promise 死锁！所有请求被永远挂起' },
        ],
      },
      {
        id: 'proper_async',
        label: '按需 async',
        description: '只有真正需要异步的才标记 async',
        style: 'craft',
        riskLevel: 'low',
        outcomes: [
          { weight: 60, level: 'success', effects: { progress: 5, codeQuality: 4, apiCost: 0.3 }, message: '优化了异步流程，代码更清晰了' },
          { weight: 30, level: 'safe', effects: { progress: 4, codeQuality: 2, apiCost: 0.3 }, message: '同步函数保持同步，异步函数才 async' },
          { weight: 10, level: 'quality_boost', effects: { progress: 6, codeQuality: 5, apiCost: 0.3 }, message: '重构异步逻辑后减少了 80% 的 await 语句' },
        ],
      },
      {
        id: 'async_layer',
        label: '外层 async',
        description: '只有最外层函数 async，内部保持同步',
        style: 'budget',
        riskLevel: 'medium',
        outcomes: [
          { weight: 50, level: 'success', effects: { progress: 6, codeQuality: 1, apiCost: 0.5 }, message: '分层清晰：外层异步协调，内层同步执行' },
          { weight: 30, level: 'minor_bug', effects: { progress: 4, bugs: 1, apiCost: 0.5 }, message: '有个内层函数后来需要变异步了，改起来有点麻烦' },
          { weight: 15, level: 'moderate', effects: { progress: 3, bugs: 2, codeQuality: -2, apiCost: 0.5 }, message: '异步边界不够清晰，有些地方的同步假设不成立' },
          { weight: 5, level: 'catastrophe', effects: { progress: 0, bugs: 3, codeQuality: -5, systemHealth: -5, apiCost: 1 }, message: '同步函数里调了个异步 API 但没等结果...' },
        ],
      },
    ],
  },

  // ============================================================
  // 因果链后续事件（6 个）— 由 causal-chains.ts 触发
  // ============================================================
  {
    id: 'chain-node-modules-explode',
    title: 'node_modules 磁盘爆满！',
    description: '之前装的 847 个包终于把磁盘撑爆了。CI 构建失败，本地也跑不起来。',
    icon: '💥',
    category: 'dependency',
    decisionType: 'emergency',
    minProgress: 15,
    maxProgress: 70,
    prerequisites: ['dep-847-packages'],
    choices: [
      {
        id: 'clean_reinstall',
        label: '清理重装',
        description: '删除 node_modules 精简重装',
        style: 'craft',
        riskLevel: 'medium',
        outcomes: [
          { weight: 50, level: 'success', effects: { progress: 5, codeQuality: 3, systemHealth: 5, apiCost: 1 }, message: '清理后只保留了必要的包，磁盘空间恢复了', clearEffect: 'tech_debt' },
          { weight: 30, level: 'minor_bug', effects: { progress: 3, bugs: 1, apiCost: 1 }, message: '清理时误删了一个还需要的包' },
          { weight: 15, level: 'moderate', effects: { progress: 1, bugs: 2, systemHealth: -5, apiCost: 2 }, message: '重装后版本变了，到处都是兼容性问题' },
          { weight: 5, level: 'catastrophe', effects: { progress: -2, bugs: 3, systemHealth: -12, apiCost: 2 }, message: 'lock 文件和实际不一致，依赖树完全混乱' },
        ],
      },
      {
        id: 'buy_more_disk',
        label: '加磁盘空间',
        description: '钱能解决的问题就不是问题',
        style: 'speed',
        riskLevel: 'low',
        isHighCost: true,
        outcomes: [
          { weight: 55, level: 'success', effects: { progress: 6, apiCost: 5 }, message: '升级到 500GB 磁盘，问题暂时解决了' },
          { weight: 30, level: 'safe', effects: { progress: 4, apiCost: 5 }, message: '花钱买了空间，治标不治本' },
          { weight: 15, level: 'minor_bug', effects: { progress: 4, apiCost: 8 }, message: '磁盘升级了，但 CI 的配额也要加钱...', applyEffect: 'budget_alert' },
        ],
      },
      {
        id: 'monorepo_split',
        label: '拆分仓库',
        description: '按模块拆分，每个子仓库装自己的包',
        style: 'budget',
        riskLevel: 'high',
        outcomes: [
          { weight: 35, level: 'success', effects: { progress: 7, codeQuality: 3, apiCost: 2 }, message: '拆分后每个子仓库包很精简，问题彻底解决' },
          { weight: 30, level: 'minor_bug', effects: { progress: 5, bugs: 1, apiCost: 2 }, message: '拆分后有些跨仓库依赖处理起来有点麻烦' },
          { weight: 25, level: 'moderate', effects: { progress: 2, bugs: 3, systemHealth: -5, apiCost: 3 }, message: '拆分引入了大量配置工作，进度反而变慢' },
          { weight: 10, level: 'catastrophe', effects: { progress: -1, bugs: 4, systemHealth: -10, apiCost: 4 }, message: '拆分后版本管理混乱，子仓库互相依赖成环' },
        ],
      },
    ],
  },
  {
    id: 'chain-regression-storm',
    title: '回归 Bug 大爆发！',
    description: '之前删掉测试的恶果来了。每次改一行代码，就有三个地方跟着坏掉。',
    icon: '🐛',
    category: 'delete',
    decisionType: 'emergency',
    minProgress: 30,
    maxProgress: 90,
    prerequisites: ['del-all-tests'],
    choices: [
      {
        id: 'emergency_tests',
        label: '紧急补测试',
        description: '通宵写测试把关键路径覆盖住',
        style: 'craft',
        riskLevel: 'medium',
        outcomes: [
          { weight: 45, level: 'success', effects: { progress: 5, codeQuality: 6, bugs: -3, systemHealth: 5, apiCost: 2 }, message: '加班补齐了关键测试，终于止住了回归潮', clearEffect: 'tech_debt' },
          { weight: 30, level: 'minor_bug', effects: { progress: 3, codeQuality: 3, bugs: -1, apiCost: 2 }, message: '补了一些测试，回归速度放缓了' },
          { weight: 18, level: 'moderate', effects: { progress: 1, bugs: 1, codeQuality: -2, apiCost: 3 }, message: '测试本身有 bug，误报让大家不信任测试了' },
          { weight: 7, level: 'catastrophe', effects: { progress: -2, bugs: 3, systemHealth: -8, apiCost: 4 }, message: '来不及了，回归 bug 比写测试的速度还快' },
        ],
      },
      {
        id: 'rollback_code',
        label: '回滚代码',
        description: '回退到有测试的那个版本',
        style: 'budget',
        riskLevel: 'high',
        outcomes: [
          { weight: 40, level: 'success', effects: { progress: -3, codeQuality: 5, bugs: -4, systemHealth: 8, apiCost: 1 }, message: '回滚成功！丢失了一些进度但系统稳定了' },
          { weight: 30, level: 'minor_bug', effects: { progress: -5, bugs: -2, systemHealth: 3, apiCost: 1 }, message: '回滚了大部分，有些改动手动恢复' },
          { weight: 20, level: 'moderate', effects: { progress: -7, bugs: -1, codeQuality: -3, apiCost: 2 }, message: '回滚不彻底，新旧代码混在一起更混乱了' },
          { weight: 10, level: 'catastrophe', effects: { progress: -10, bugs: 2, systemHealth: -10, apiCost: 2 }, message: '回滚操作本身引入了数据不一致！' },
        ],
      },
      {
        id: 'hotfix_whack',
        label: '逐个热修',
        description: '打地鼠式修 bug，哪个最严重修哪个',
        style: 'speed',
        riskLevel: 'high',
        outcomes: [
          { weight: 30, level: 'success', effects: { progress: 6, bugs: -2, apiCost: 2 }, message: '主要 bug 修完了，虽然代码变更丑了' },
          { weight: 30, level: 'minor_bug', effects: { progress: 4, bugs: 0, apiCost: 2 }, message: '修了 5 个但又冒出了 3 个新的' },
          { weight: 25, level: 'moderate', effects: { progress: 2, bugs: 2, codeQuality: -5, systemHealth: -5, apiCost: 3 }, message: '热修复引入了更多问题，代码质量持续下降', applyEffect: 'fragile_arch' },
          { weight: 15, level: 'catastrophe', effects: { progress: -1, bugs: 4, systemHealth: -15, apiCost: 4 }, message: '热修复互相冲突，系统进入不可预测状态' },
        ],
      },
    ],
  },
  {
    id: 'chain-key-leaked',
    title: '密钥泄露事件！',
    description: '之前提交的 API Key 被 GitHub 机器人扫描到了，有人正在盗用你的额度。',
    icon: '🚨',
    category: 'yolo',
    decisionType: 'emergency',
    minProgress: 20,
    maxProgress: 95,
    prerequisites: ['yolo-commit-keys'],
    choices: [
      {
        id: 'rotate_immediately',
        label: '立即轮换',
        description: '作废旧密钥，生成新的，全面替换',
        style: 'craft',
        riskLevel: 'medium',
        outcomes: [
          { weight: 50, level: 'success', effects: { progress: 3, systemHealth: 8, apiCost: 3 }, message: '密钥轮换完成！虽然花了时间但堵住了漏洞', clearEffect: 'budget_alert' },
          { weight: 30, level: 'minor_bug', effects: { progress: 1, bugs: 1, apiCost: 5 }, message: '轮换后有一个服务忘了更新密钥，挂了几分钟' },
          { weight: 15, level: 'moderate', effects: { progress: -1, bugs: 2, systemHealth: -5, apiCost: 8 }, message: '轮换期间服务中断，部分用户受影响' },
          { weight: 5, level: 'catastrophe', effects: { progress: -3, systemHealth: -12, apiCost: 12 }, message: '新密钥也被 commit 到了仓库... 历史重演' },
        ],
      },
      {
        id: 'ignore_pray',
        label: '假装没看到',
        description: '也许没人注意到？先别动...',
        style: 'gambler',
        riskLevel: 'extreme',
        outcomes: [
          { weight: 20, level: 'success', effects: { progress: 6, apiCost: 5 }, message: '运气好，攻击者似乎还没利用这个密钥' },
          { weight: 25, level: 'minor_bug', effects: { progress: 4, apiCost: 10 }, message: '账单多了一些异常调用，但还在可控范围' },
          { weight: 35, level: 'moderate', effects: { progress: 0, systemHealth: -15, apiCost: 20 }, message: '密钥被大量盗用，这个月账单翻了 5 倍', applyEffect: 'budget_alert' },
          { weight: 20, level: 'catastrophe', effects: { progress: -5, systemHealth: -25, apiCost: 30 }, message: '攻击者通过密钥获取了数据库访问权限！' },
        ],
      },
      {
        id: 'limit_and_monitor',
        label: '限速+监控',
        description: '先给密钥设限额，同时准备替换方案',
        style: 'budget',
        riskLevel: 'medium',
        outcomes: [
          { weight: 45, level: 'success', effects: { progress: 4, systemHealth: 5, apiCost: 2 }, message: '设了限额拦住了异常调用，争取了时间做彻底修复' },
          { weight: 30, level: 'minor_bug', effects: { progress: 3, apiCost: 4 }, message: '限额太低把正常调用也拦了，需要微调' },
          { weight: 20, level: 'moderate', effects: { progress: 1, systemHealth: -5, apiCost: 6 }, message: '攻击者在限额生效前已经烧了不少额度' },
          { weight: 5, level: 'catastrophe', effects: { progress: -2, systemHealth: -15, apiCost: 10 }, message: '攻击者找到了绕过限额的方法' },
        ],
      },
    ],
  },
  {
    id: 'chain-type-chaos',
    title: '类型混乱大崩溃',
    description: '去掉 TypeScript 后，string 和 number 开始混打，undefined 满天飞。',
    icon: '🌪️',
    category: 'refactor',
    decisionType: 'emergency',
    minProgress: 30,
    maxProgress: 90,
    prerequisites: ['ref-remove-ts'],
    choices: [
      {
        id: 'restore_ts',
        label: '加回 TS',
        description: '承认错误，重新加入类型系统',
        style: 'craft',
        riskLevel: 'medium',
        outcomes: [
          { weight: 45, level: 'success', effects: { progress: 3, codeQuality: 8, bugs: -3, systemHealth: 5, apiCost: 2 }, message: '加回 TypeScript 后一次性发现了 15 个类型错误！', clearEffect: 'tech_debt' },
          { weight: 30, level: 'minor_bug', effects: { progress: 1, codeQuality: 4, bugs: -1, apiCost: 2 }, message: '加回了但有些地方只能先用 any 过渡' },
          { weight: 20, level: 'moderate', effects: { progress: -2, codeQuality: 1, bugs: 1, apiCost: 3 }, message: '类型迁移过程中代码大面积标红' },
          { weight: 5, level: 'catastrophe', effects: { progress: -4, bugs: 2, systemHealth: -8, apiCost: 4 }, message: '加回 TS 后编译错误 200+，短时间内无法解决' },
        ],
      },
      {
        id: 'runtime_checks',
        label: '加运行时检查',
        description: '不加类型，但用 Zod 等做运行时校验',
        style: 'budget',
        riskLevel: 'medium',
        outcomes: [
          { weight: 40, level: 'success', effects: { progress: 5, codeQuality: 3, bugs: -2, apiCost: 1.5 }, message: '运行时校验拦住了大部分类型错误' },
          { weight: 30, level: 'minor_bug', effects: { progress: 3, bugs: -1, apiCost: 1.5 }, message: '校验覆盖了主要入口，但内部函数还是裸奔' },
          { weight: 22, level: 'moderate', effects: { progress: 1, bugs: 1, codeQuality: -2, systemHealth: -3, apiCost: 2 }, message: '运行时校验的性能开销比想象中大' },
          { weight: 8, level: 'catastrophe', effects: { progress: -1, bugs: 3, systemHealth: -10, apiCost: 2 }, message: '校验报错太多被人静默了，等于没校验' },
        ],
      },
      {
        id: 'just_fix_bugs',
        label: '逐个修 bug',
        description: '哪里报错修哪里，不改架构',
        style: 'speed',
        riskLevel: 'high',
        outcomes: [
          { weight: 30, level: 'success', effects: { progress: 7, bugs: -2, apiCost: 1 }, message: '把最显眼的类型相关 bug 修好了' },
          { weight: 30, level: 'minor_bug', effects: { progress: 5, bugs: 0, apiCost: 1 }, message: '修了几个但新的类型错误还在冒' },
          { weight: 25, level: 'moderate', effects: { progress: 3, bugs: 2, codeQuality: -5, apiCost: 1.5 }, message: '打地鼠式修 bug 越修越多' },
          { weight: 15, level: 'catastrophe', effects: { progress: 0, bugs: 4, systemHealth: -12, apiCost: 2 }, message: '修了一个类型 bug 导致三个新 bug，恶性循环' },
        ],
      },
    ],
  },
  {
    id: 'chain-production-fire',
    title: '生产环境大火！',
    description: '上次未测试部署的代码炸了。用户收到了随机错误，数据可能不一致。',
    icon: '🔥',
    category: 'deploy',
    decisionType: 'emergency',
    minProgress: 40,
    maxProgress: 95,
    prerequisites: ['deploy-untested-prod'],
    choices: [
      {
        id: 'emergency_rollback',
        label: '紧急回滚',
        description: '先回滚到上一个稳定版本',
        style: 'craft',
        riskLevel: 'medium',
        outcomes: [
          { weight: 50, level: 'success', effects: { progress: -2, codeQuality: 2, bugs: -3, systemHealth: 10, apiCost: 2 }, message: '成功回滚！用户体验恢复，数据没丢', clearEffect: 'fragile_arch' },
          { weight: 30, level: 'minor_bug', effects: { progress: -4, bugs: -1, systemHealth: 5, apiCost: 2 }, message: '回滚了但有几分钟的数据需要手动修复' },
          { weight: 15, level: 'moderate', effects: { progress: -6, bugs: 1, systemHealth: -3, apiCost: 3 }, message: '回滚过程本身出了问题，延长了故障时间' },
          { weight: 5, level: 'catastrophe', effects: { progress: -8, bugs: 2, systemHealth: -10, apiCost: 4 }, message: '回滚失败！上个版本的镜像找不到了' },
        ],
      },
      {
        id: 'hotfix_forward',
        label: '向前修复',
        description: '不回滚，直接修复当前版本的 bug',
        style: 'speed',
        riskLevel: 'high',
        outcomes: [
          { weight: 35, level: 'success', effects: { progress: 5, bugs: -2, systemHealth: 5, apiCost: 3 }, message: '10 分钟内定位并修复了问题，向前部署成功！' },
          { weight: 30, level: 'minor_bug', effects: { progress: 3, bugs: 0, apiCost: 3 }, message: '修了主要问题但还有些小毛病' },
          { weight: 25, level: 'moderate', effects: { progress: 0, bugs: 2, systemHealth: -8, apiCost: 4 }, message: '修复引入了新问题，局面更糟了' },
          { weight: 10, level: 'catastrophe', effects: { progress: -3, bugs: 4, systemHealth: -18, apiCost: 5 }, message: '热修复把数据搞得更乱了，必须全面回滚' },
        ],
      },
      {
        id: 'maintenance_mode',
        label: '挂维护页',
        description: '先让网站下线，争取时间排查',
        style: 'budget',
        riskLevel: 'medium',
        outcomes: [
          { weight: 45, level: 'success', effects: { progress: 0, bugs: -2, systemHealth: 8, apiCost: 1 }, message: '维护模式赢得了时间，从容修复后重新上线' },
          { weight: 30, level: 'minor_bug', effects: { progress: -2, bugs: -1, systemHealth: 3, apiCost: 1 }, message: '维护了半小时，修好了大部分问题' },
          { weight: 20, level: 'moderate', effects: { progress: -4, systemHealth: -3, apiCost: 2 }, message: '维护时间太长，用户开始不耐烦了', applyEffect: 'low_morale' },
          { weight: 5, level: 'catastrophe', effects: { progress: -6, systemHealth: -8, apiCost: 3 }, message: '维护页面本身挂了... 连 503 都看不到' },
        ],
      },
    ],
  },
  {
    id: 'chain-cascading-crash',
    title: '白屏连环崩溃',
    description: '之前移除错误处理的后果：一个小异常引发了连锁反应，页面不断白屏。',
    icon: '⚪',
    category: 'delete',
    decisionType: 'emergency',
    minProgress: 30,
    maxProgress: 90,
    prerequisites: ['del-error-handling'],
    choices: [
      {
        id: 'add_error_boundary',
        label: '加错误边界',
        description: '用 React Error Boundary 兜底',
        style: 'craft',
        riskLevel: 'low',
        outcomes: [
          { weight: 55, level: 'success', effects: { progress: 4, codeQuality: 5, bugs: -2, systemHealth: 8, apiCost: 1 }, message: 'Error Boundary 兜住了崩溃，用户至少能看到友好提示', clearEffect: 'fragile_arch' },
          { weight: 30, level: 'minor_bug', effects: { progress: 2, codeQuality: 3, bugs: -1, systemHealth: 3, apiCost: 1 }, message: 'Boundary 拦住了大部分崩溃，但有些位置漏了' },
          { weight: 12, level: 'moderate', effects: { progress: 0, bugs: 1, systemHealth: -3, apiCost: 1.5 }, message: 'Boundary 太多了，错误被吞掉难以排查' },
          { weight: 3, level: 'catastrophe', effects: { progress: -2, bugs: 2, systemHealth: -8, apiCost: 2 }, message: 'Error Boundary 本身有 bug，引发了更多白屏' },
        ],
      },
      {
        id: 'restore_try_catch',
        label: '恢复 try-catch',
        description: '把之前删掉的错误处理逐步加回来',
        style: 'budget',
        riskLevel: 'medium',
        outcomes: [
          { weight: 45, level: 'success', effects: { progress: 3, codeQuality: 6, bugs: -3, systemHealth: 10, apiCost: 2 }, message: '逐步恢复了错误处理，系统重新稳定', clearEffect: 'fragile_arch' },
          { weight: 30, level: 'minor_bug', effects: { progress: 1, codeQuality: 3, bugs: -1, systemHealth: 5, apiCost: 2 }, message: '恢复了关键部分，但不确定是否覆盖完全' },
          { weight: 20, level: 'moderate', effects: { progress: -1, bugs: 1, codeQuality: -2, apiCost: 2.5 }, message: '新的 catch 逻辑和旧代码不兼容' },
          { weight: 5, level: 'catastrophe', effects: { progress: -3, bugs: 2, systemHealth: -5, apiCost: 3 }, message: '恢复过程中改错了，白屏更频繁了' },
        ],
      },
      {
        id: 'restart_loop',
        label: '自动重启',
        description: '崩溃就重启，用 PM2 保活',
        style: 'speed',
        riskLevel: 'high',
        outcomes: [
          { weight: 30, level: 'success', effects: { progress: 6, systemHealth: 3, apiCost: 1 }, message: 'PM2 持续保活，用户只感受到短暂闪烁' },
          { weight: 30, level: 'minor_bug', effects: { progress: 4, bugs: 1, systemHealth: -2, apiCost: 1 }, message: '不断重启让内存占用越来越高' },
          { weight: 25, level: 'moderate', effects: { progress: 2, bugs: 2, systemHealth: -10, apiCost: 2 }, message: '重启频率太高，每秒重启一次，CPU 100%' },
          { weight: 15, level: 'catastrophe', effects: { progress: -2, bugs: 3, systemHealth: -18, apiCost: 3 }, message: '无限重启循环导致文件锁死，必须人工介入' },
        ],
      },
    ],
  },
]
