import type { ProjectConfig } from '@/types'

export const PROJECTS: ProjectConfig[] = [
  {
    id: 'todo-blockchain',
    name: 'Blockchain TODO App',
    description: '一个待办事项而已，为什么不上链呢？每完成一个任务奖励你 0.0001 个币。',
    icon: '⛓️',
    difficulty: 'easy',
    features: [
      '区块链钱包集成',
      '智能合约 TODO',
      'NFT 任务标记',
      '去中心化存储',
      '代币奖励系统',
    ],
    riskProfile: {
      categoryWeights: {
        dependency: 1.2,
        deploy: 1.3,
        yolo: 1.4,
        feature: 1.0,
        refactor: 0.8,
        delete: 0.9,
      },
      recommendedStyle: 'gambler',
      milestoneNames: {
        init: '搭建钱包环境',
        core: '智能合约开发',
        crisis: '代币经济审计',
        test: '测试网部署',
        launch: '主网上线',
      },
    },
  },
  {
    id: 'ai-calculator',
    name: 'AI-Powered Calculator',
    description: '1+1=? 让我调用 5 个大模型 API 投票决定。准确率高达 97%！',
    icon: '🤖',
    difficulty: 'easy',
    features: [
      'GPT 数学引擎',
      '语音输入识别',
      'AR 计算可视化',
      '情感化计算结果',
      '计算历史区块链存储',
    ],
    riskProfile: {
      categoryWeights: {
        dependency: 1.3,
        feature: 1.2,
        deploy: 0.9,
        yolo: 1.0,
        refactor: 1.0,
        delete: 0.8,
      },
      recommendedStyle: 'budget',
      milestoneNames: {
        init: '选择 AI 模型',
        core: '多模型集成',
        crisis: 'API 成本失控',
        test: '精度验证',
        launch: '计算器上线',
      },
    },
  },
  {
    id: 'social-pet',
    name: 'Social Media for Pets',
    description: '你的猫终于可以发朋友圈了。AI 自动帮它 P 图、写文案、怼评论。',
    icon: '🐱',
    difficulty: 'normal',
    features: [
      '宠物 AI 自拍',
      '汪星人匹配算法',
      '猫语翻译器',
      '宠物 NFT 头像',
      '遛狗路线 AI 优化',
      '宠物情绪分析',
    ],
    riskProfile: {
      categoryWeights: {
        feature: 1.5,
        dependency: 1.0,
        deploy: 1.1,
        yolo: 1.0,
        refactor: 0.9,
        delete: 0.8,
      },
      recommendedStyle: 'speed',
      milestoneNames: {
        init: '宠物档案搭建',
        core: '社交功能开发',
        crisis: '需求膨胀失控',
        test: '萌宠内测',
        launch: '全网上线',
      },
    },
  },
  {
    id: 'dating-plant',
    name: 'Plant Dating App',
    description: '帮你的绿萝找到真爱。基于光合作用频率的 AI 匹配，成功率比人类交友还高。',
    icon: '🌱',
    difficulty: 'normal',
    features: [
      '植物兼容性 AI 匹配',
      '光合作用社交评分',
      '盆栽 AR 约会场景',
      '浇水提醒智能合约',
      '植物情绪 IoT 传感器',
      '花语 AI 翻译',
    ],
    riskProfile: {
      categoryWeights: {
        refactor: 1.4,
        dependency: 1.2,
        feature: 1.0,
        deploy: 1.0,
        yolo: 0.7,
        delete: 0.9,
      },
      recommendedStyle: 'craft',
      milestoneNames: {
        init: '传感器选型',
        core: 'IoT 集成开发',
        crisis: '硬件兼容危机',
        test: '温室环境测试',
        launch: '花房上线',
      },
    },
  },
  {
    id: 'startup-os',
    name: 'Startup Operating System',
    description: '一键生成 PPT、计算烧钱速率、预测下一次 pivot。创业从未如此科学（和离谱）。',
    icon: '🚀',
    difficulty: 'hard',
    features: [
      'AI CEO 决策引擎',
      '融资 PPT 自动生成',
      '员工情绪量子分析',
      '竞品 AI 间谍系统',
      '自动 pivot 检测',
      '烧钱速率 Dashboard',
      '独角兽概率计算器',
    ],
    riskProfile: {
      categoryWeights: {
        feature: 1.3,
        deploy: 1.3,
        yolo: 1.5,
        dependency: 1.0,
        refactor: 1.0,
        delete: 1.0,
      },
      recommendedStyle: 'gambler',
      milestoneNames: {
        init: '融资准备',
        core: '核心 MVP 开发',
        crisis: '投资人施压',
        test: 'Demo Day 彩排',
        launch: 'Product Hunt 首发',
      },
    },
  },
  {
    id: 'metaverse-excel',
    name: 'Metaverse Excel',
    description: '在元宇宙里做报表，用 VR 拖拽单元格，每个公式都经过区块链验证。老板看了直摇头。',
    icon: '🌐',
    difficulty: 'hard',
    features: [
      'VR 电子表格',
      '3D 数据透视表',
      '元宇宙公式编辑器',
      '区块链单元格验证',
      'AI 自动填充预言机',
      '量子计算加速',
      'NFT 图表生成',
    ],
    riskProfile: {
      categoryWeights: {
        refactor: 1.5,
        deploy: 1.4,
        dependency: 1.2,
        feature: 1.0,
        yolo: 0.8,
        delete: 0.9,
      },
      recommendedStyle: 'craft',
      milestoneNames: {
        init: 'VR 环境搭建',
        core: '3D 渲染引擎',
        crisis: '性能瓶颈爆发',
        test: 'VR 眩晕测试',
        launch: '元宇宙发布会',
      },
    },
  },
]
